steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/atlas-k8s/shortener:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    arg:
      - 'build'
      - 'tag'
      - 'gcr.io/atlas-k8s/shortener:$SHORT_SHA'
      - 'gcr.io/atlas-k8s/shortener:latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/atlas-k8s/shortener:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/atlas-k8s/shortener:latest']
