steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/atlas-k8s/shortener:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'gcr.io/atlas-k8s/shortener:latest'
      - '-t'
      - 'gcr.io/atlas-k8s/shortener:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'gcr.io/atlas-k8s/shortener:$SHORT_SHA'
      - 'gcr.io/atlas-k8s/shortener:latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/atlas-k8s/shortener:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/atlas-k8s/shortener:latest']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      [
        'run',
        '--version',
        '$SHORT_SHA',
        '--project',
        'atlas-k8s',
        '--cluster',
        'atlas-k8s-n',
        '--location',
        'europe-north1-b',
        '--image',
        'gcr.io/atlas-k8s/shortener:$SHORT_SHA',
        '--filename',
        './k8s',
      ]
