version: "3"

services:
  app:
    build: .
    env_file: .env
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - shortener-db:/var/lib/postgresql/data

volumes:
  shortener-db: