apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
  namespace: shortener
  labels:
    app: shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      serviceAccountName: shortener
      nodeSelector:
        production: 'true'
      containers:
        - name: shortener
          image: gcr.io/atlas-k8s/shortener:latest
          resources:
            requests:
              cpu: '250m'
          envFrom:
            - configMapRef:
                name: dotenv
          ports:
            - containerPort: 3000
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: shortener
  namespace: shortener
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: shortener
